// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cr/tec/genetic/protobuf/Employee.proto

package cr.tec.genetic.struct;

public final class EmployeeProto {
  private EmployeeProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface EmployeeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:genetic.Employee)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string firstname = 1;</code>
     */
    java.lang.String getFirstname();
    /**
     * <code>string firstname = 1;</code>
     */
    com.google.protobuf.ByteString
        getFirstnameBytes();

    /**
     * <code>string lastname = 2;</code>
     */
    java.lang.String getLastname();
    /**
     * <code>string lastname = 2;</code>
     */
    com.google.protobuf.ByteString
        getLastnameBytes();

    /**
     * <code>int32 id = 3;</code>
     */
    int getId();

    /**
     * <code>double salary = 4;</code>
     */
    double getSalary();

    /**
     * <code>repeated .genetic.Department dept = 5;</code>
     */
    java.util.List<cr.tec.genetic.struct.EmployeeProto.Department> 
        getDeptList();
    /**
     * <code>repeated .genetic.Department dept = 5;</code>
     */
    cr.tec.genetic.struct.EmployeeProto.Department getDept(int index);
    /**
     * <code>repeated .genetic.Department dept = 5;</code>
     */
    int getDeptCount();
    /**
     * <code>repeated .genetic.Department dept = 5;</code>
     */
    java.util.List<? extends cr.tec.genetic.struct.EmployeeProto.DepartmentOrBuilder> 
        getDeptOrBuilderList();
    /**
     * <code>repeated .genetic.Department dept = 5;</code>
     */
    cr.tec.genetic.struct.EmployeeProto.DepartmentOrBuilder getDeptOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code genetic.Employee}
   */
  public  static final class Employee extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:genetic.Employee)
      EmployeeOrBuilder {
    // Use Employee.newBuilder() to construct.
    private Employee(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Employee() {
      firstname_ = "";
      lastname_ = "";
      id_ = 0;
      salary_ = 0D;
      dept_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Employee(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              firstname_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              lastname_ = s;
              break;
            }
            case 24: {

              id_ = input.readInt32();
              break;
            }
            case 33: {

              salary_ = input.readDouble();
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                dept_ = new java.util.ArrayList<cr.tec.genetic.struct.EmployeeProto.Department>();
                mutable_bitField0_ |= 0x00000010;
              }
              dept_.add(
                  input.readMessage(cr.tec.genetic.struct.EmployeeProto.Department.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          dept_ = java.util.Collections.unmodifiableList(dept_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cr.tec.genetic.struct.EmployeeProto.internal_static_genetic_Employee_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cr.tec.genetic.struct.EmployeeProto.internal_static_genetic_Employee_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cr.tec.genetic.struct.EmployeeProto.Employee.class, cr.tec.genetic.struct.EmployeeProto.Employee.Builder.class);
    }

    private int bitField0_;
    public static final int FIRSTNAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object firstname_;
    /**
     * <code>string firstname = 1;</code>
     */
    public java.lang.String getFirstname() {
      java.lang.Object ref = firstname_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        firstname_ = s;
        return s;
      }
    }
    /**
     * <code>string firstname = 1;</code>
     */
    public com.google.protobuf.ByteString
        getFirstnameBytes() {
      java.lang.Object ref = firstname_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        firstname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LASTNAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object lastname_;
    /**
     * <code>string lastname = 2;</code>
     */
    public java.lang.String getLastname() {
      java.lang.Object ref = lastname_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lastname_ = s;
        return s;
      }
    }
    /**
     * <code>string lastname = 2;</code>
     */
    public com.google.protobuf.ByteString
        getLastnameBytes() {
      java.lang.Object ref = lastname_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lastname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ID_FIELD_NUMBER = 3;
    private int id_;
    /**
     * <code>int32 id = 3;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int SALARY_FIELD_NUMBER = 4;
    private double salary_;
    /**
     * <code>double salary = 4;</code>
     */
    public double getSalary() {
      return salary_;
    }

    public static final int DEPT_FIELD_NUMBER = 5;
    private java.util.List<cr.tec.genetic.struct.EmployeeProto.Department> dept_;
    /**
     * <code>repeated .genetic.Department dept = 5;</code>
     */
    public java.util.List<cr.tec.genetic.struct.EmployeeProto.Department> getDeptList() {
      return dept_;
    }
    /**
     * <code>repeated .genetic.Department dept = 5;</code>
     */
    public java.util.List<? extends cr.tec.genetic.struct.EmployeeProto.DepartmentOrBuilder> 
        getDeptOrBuilderList() {
      return dept_;
    }
    /**
     * <code>repeated .genetic.Department dept = 5;</code>
     */
    public int getDeptCount() {
      return dept_.size();
    }
    /**
     * <code>repeated .genetic.Department dept = 5;</code>
     */
    public cr.tec.genetic.struct.EmployeeProto.Department getDept(int index) {
      return dept_.get(index);
    }
    /**
     * <code>repeated .genetic.Department dept = 5;</code>
     */
    public cr.tec.genetic.struct.EmployeeProto.DepartmentOrBuilder getDeptOrBuilder(
        int index) {
      return dept_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getFirstnameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, firstname_);
      }
      if (!getLastnameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, lastname_);
      }
      if (id_ != 0) {
        output.writeInt32(3, id_);
      }
      if (salary_ != 0D) {
        output.writeDouble(4, salary_);
      }
      for (int i = 0; i < dept_.size(); i++) {
        output.writeMessage(5, dept_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getFirstnameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, firstname_);
      }
      if (!getLastnameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, lastname_);
      }
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, id_);
      }
      if (salary_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, salary_);
      }
      for (int i = 0; i < dept_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, dept_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cr.tec.genetic.struct.EmployeeProto.Employee)) {
        return super.equals(obj);
      }
      cr.tec.genetic.struct.EmployeeProto.Employee other = (cr.tec.genetic.struct.EmployeeProto.Employee) obj;

      boolean result = true;
      result = result && getFirstname()
          .equals(other.getFirstname());
      result = result && getLastname()
          .equals(other.getLastname());
      result = result && (getId()
          == other.getId());
      result = result && (
          java.lang.Double.doubleToLongBits(getSalary())
          == java.lang.Double.doubleToLongBits(
              other.getSalary()));
      result = result && getDeptList()
          .equals(other.getDeptList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FIRSTNAME_FIELD_NUMBER;
      hash = (53 * hash) + getFirstname().hashCode();
      hash = (37 * hash) + LASTNAME_FIELD_NUMBER;
      hash = (53 * hash) + getLastname().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + SALARY_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getSalary()));
      if (getDeptCount() > 0) {
        hash = (37 * hash) + DEPT_FIELD_NUMBER;
        hash = (53 * hash) + getDeptList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cr.tec.genetic.struct.EmployeeProto.Employee parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cr.tec.genetic.struct.EmployeeProto.Employee parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cr.tec.genetic.struct.EmployeeProto.Employee parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cr.tec.genetic.struct.EmployeeProto.Employee parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cr.tec.genetic.struct.EmployeeProto.Employee parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cr.tec.genetic.struct.EmployeeProto.Employee parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cr.tec.genetic.struct.EmployeeProto.Employee parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cr.tec.genetic.struct.EmployeeProto.Employee parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cr.tec.genetic.struct.EmployeeProto.Employee parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cr.tec.genetic.struct.EmployeeProto.Employee parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cr.tec.genetic.struct.EmployeeProto.Employee parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cr.tec.genetic.struct.EmployeeProto.Employee parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cr.tec.genetic.struct.EmployeeProto.Employee prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code genetic.Employee}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:genetic.Employee)
        cr.tec.genetic.struct.EmployeeProto.EmployeeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cr.tec.genetic.struct.EmployeeProto.internal_static_genetic_Employee_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cr.tec.genetic.struct.EmployeeProto.internal_static_genetic_Employee_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cr.tec.genetic.struct.EmployeeProto.Employee.class, cr.tec.genetic.struct.EmployeeProto.Employee.Builder.class);
      }

      // Construct using cr.tec.genetic.struct.EmployeeProto.Employee.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getDeptFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        firstname_ = "";

        lastname_ = "";

        id_ = 0;

        salary_ = 0D;

        if (deptBuilder_ == null) {
          dept_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
        } else {
          deptBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cr.tec.genetic.struct.EmployeeProto.internal_static_genetic_Employee_descriptor;
      }

      public cr.tec.genetic.struct.EmployeeProto.Employee getDefaultInstanceForType() {
        return cr.tec.genetic.struct.EmployeeProto.Employee.getDefaultInstance();
      }

      public cr.tec.genetic.struct.EmployeeProto.Employee build() {
        cr.tec.genetic.struct.EmployeeProto.Employee result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cr.tec.genetic.struct.EmployeeProto.Employee buildPartial() {
        cr.tec.genetic.struct.EmployeeProto.Employee result = new cr.tec.genetic.struct.EmployeeProto.Employee(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.firstname_ = firstname_;
        result.lastname_ = lastname_;
        result.id_ = id_;
        result.salary_ = salary_;
        if (deptBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010)) {
            dept_ = java.util.Collections.unmodifiableList(dept_);
            bitField0_ = (bitField0_ & ~0x00000010);
          }
          result.dept_ = dept_;
        } else {
          result.dept_ = deptBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cr.tec.genetic.struct.EmployeeProto.Employee) {
          return mergeFrom((cr.tec.genetic.struct.EmployeeProto.Employee)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cr.tec.genetic.struct.EmployeeProto.Employee other) {
        if (other == cr.tec.genetic.struct.EmployeeProto.Employee.getDefaultInstance()) return this;
        if (!other.getFirstname().isEmpty()) {
          firstname_ = other.firstname_;
          onChanged();
        }
        if (!other.getLastname().isEmpty()) {
          lastname_ = other.lastname_;
          onChanged();
        }
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (other.getSalary() != 0D) {
          setSalary(other.getSalary());
        }
        if (deptBuilder_ == null) {
          if (!other.dept_.isEmpty()) {
            if (dept_.isEmpty()) {
              dept_ = other.dept_;
              bitField0_ = (bitField0_ & ~0x00000010);
            } else {
              ensureDeptIsMutable();
              dept_.addAll(other.dept_);
            }
            onChanged();
          }
        } else {
          if (!other.dept_.isEmpty()) {
            if (deptBuilder_.isEmpty()) {
              deptBuilder_.dispose();
              deptBuilder_ = null;
              dept_ = other.dept_;
              bitField0_ = (bitField0_ & ~0x00000010);
              deptBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getDeptFieldBuilder() : null;
            } else {
              deptBuilder_.addAllMessages(other.dept_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cr.tec.genetic.struct.EmployeeProto.Employee parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cr.tec.genetic.struct.EmployeeProto.Employee) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object firstname_ = "";
      /**
       * <code>string firstname = 1;</code>
       */
      public java.lang.String getFirstname() {
        java.lang.Object ref = firstname_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          firstname_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string firstname = 1;</code>
       */
      public com.google.protobuf.ByteString
          getFirstnameBytes() {
        java.lang.Object ref = firstname_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          firstname_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string firstname = 1;</code>
       */
      public Builder setFirstname(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        firstname_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string firstname = 1;</code>
       */
      public Builder clearFirstname() {
        
        firstname_ = getDefaultInstance().getFirstname();
        onChanged();
        return this;
      }
      /**
       * <code>string firstname = 1;</code>
       */
      public Builder setFirstnameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        firstname_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object lastname_ = "";
      /**
       * <code>string lastname = 2;</code>
       */
      public java.lang.String getLastname() {
        java.lang.Object ref = lastname_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          lastname_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string lastname = 2;</code>
       */
      public com.google.protobuf.ByteString
          getLastnameBytes() {
        java.lang.Object ref = lastname_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          lastname_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string lastname = 2;</code>
       */
      public Builder setLastname(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        lastname_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string lastname = 2;</code>
       */
      public Builder clearLastname() {
        
        lastname_ = getDefaultInstance().getLastname();
        onChanged();
        return this;
      }
      /**
       * <code>string lastname = 2;</code>
       */
      public Builder setLastnameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        lastname_ = value;
        onChanged();
        return this;
      }

      private int id_ ;
      /**
       * <code>int32 id = 3;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 3;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 3;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private double salary_ ;
      /**
       * <code>double salary = 4;</code>
       */
      public double getSalary() {
        return salary_;
      }
      /**
       * <code>double salary = 4;</code>
       */
      public Builder setSalary(double value) {
        
        salary_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double salary = 4;</code>
       */
      public Builder clearSalary() {
        
        salary_ = 0D;
        onChanged();
        return this;
      }

      private java.util.List<cr.tec.genetic.struct.EmployeeProto.Department> dept_ =
        java.util.Collections.emptyList();
      private void ensureDeptIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          dept_ = new java.util.ArrayList<cr.tec.genetic.struct.EmployeeProto.Department>(dept_);
          bitField0_ |= 0x00000010;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          cr.tec.genetic.struct.EmployeeProto.Department, cr.tec.genetic.struct.EmployeeProto.Department.Builder, cr.tec.genetic.struct.EmployeeProto.DepartmentOrBuilder> deptBuilder_;

      /**
       * <code>repeated .genetic.Department dept = 5;</code>
       */
      public java.util.List<cr.tec.genetic.struct.EmployeeProto.Department> getDeptList() {
        if (deptBuilder_ == null) {
          return java.util.Collections.unmodifiableList(dept_);
        } else {
          return deptBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .genetic.Department dept = 5;</code>
       */
      public int getDeptCount() {
        if (deptBuilder_ == null) {
          return dept_.size();
        } else {
          return deptBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .genetic.Department dept = 5;</code>
       */
      public cr.tec.genetic.struct.EmployeeProto.Department getDept(int index) {
        if (deptBuilder_ == null) {
          return dept_.get(index);
        } else {
          return deptBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .genetic.Department dept = 5;</code>
       */
      public Builder setDept(
          int index, cr.tec.genetic.struct.EmployeeProto.Department value) {
        if (deptBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDeptIsMutable();
          dept_.set(index, value);
          onChanged();
        } else {
          deptBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .genetic.Department dept = 5;</code>
       */
      public Builder setDept(
          int index, cr.tec.genetic.struct.EmployeeProto.Department.Builder builderForValue) {
        if (deptBuilder_ == null) {
          ensureDeptIsMutable();
          dept_.set(index, builderForValue.build());
          onChanged();
        } else {
          deptBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .genetic.Department dept = 5;</code>
       */
      public Builder addDept(cr.tec.genetic.struct.EmployeeProto.Department value) {
        if (deptBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDeptIsMutable();
          dept_.add(value);
          onChanged();
        } else {
          deptBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .genetic.Department dept = 5;</code>
       */
      public Builder addDept(
          int index, cr.tec.genetic.struct.EmployeeProto.Department value) {
        if (deptBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDeptIsMutable();
          dept_.add(index, value);
          onChanged();
        } else {
          deptBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .genetic.Department dept = 5;</code>
       */
      public Builder addDept(
          cr.tec.genetic.struct.EmployeeProto.Department.Builder builderForValue) {
        if (deptBuilder_ == null) {
          ensureDeptIsMutable();
          dept_.add(builderForValue.build());
          onChanged();
        } else {
          deptBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .genetic.Department dept = 5;</code>
       */
      public Builder addDept(
          int index, cr.tec.genetic.struct.EmployeeProto.Department.Builder builderForValue) {
        if (deptBuilder_ == null) {
          ensureDeptIsMutable();
          dept_.add(index, builderForValue.build());
          onChanged();
        } else {
          deptBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .genetic.Department dept = 5;</code>
       */
      public Builder addAllDept(
          java.lang.Iterable<? extends cr.tec.genetic.struct.EmployeeProto.Department> values) {
        if (deptBuilder_ == null) {
          ensureDeptIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, dept_);
          onChanged();
        } else {
          deptBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .genetic.Department dept = 5;</code>
       */
      public Builder clearDept() {
        if (deptBuilder_ == null) {
          dept_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
          onChanged();
        } else {
          deptBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .genetic.Department dept = 5;</code>
       */
      public Builder removeDept(int index) {
        if (deptBuilder_ == null) {
          ensureDeptIsMutable();
          dept_.remove(index);
          onChanged();
        } else {
          deptBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .genetic.Department dept = 5;</code>
       */
      public cr.tec.genetic.struct.EmployeeProto.Department.Builder getDeptBuilder(
          int index) {
        return getDeptFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .genetic.Department dept = 5;</code>
       */
      public cr.tec.genetic.struct.EmployeeProto.DepartmentOrBuilder getDeptOrBuilder(
          int index) {
        if (deptBuilder_ == null) {
          return dept_.get(index);  } else {
          return deptBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .genetic.Department dept = 5;</code>
       */
      public java.util.List<? extends cr.tec.genetic.struct.EmployeeProto.DepartmentOrBuilder> 
           getDeptOrBuilderList() {
        if (deptBuilder_ != null) {
          return deptBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(dept_);
        }
      }
      /**
       * <code>repeated .genetic.Department dept = 5;</code>
       */
      public cr.tec.genetic.struct.EmployeeProto.Department.Builder addDeptBuilder() {
        return getDeptFieldBuilder().addBuilder(
            cr.tec.genetic.struct.EmployeeProto.Department.getDefaultInstance());
      }
      /**
       * <code>repeated .genetic.Department dept = 5;</code>
       */
      public cr.tec.genetic.struct.EmployeeProto.Department.Builder addDeptBuilder(
          int index) {
        return getDeptFieldBuilder().addBuilder(
            index, cr.tec.genetic.struct.EmployeeProto.Department.getDefaultInstance());
      }
      /**
       * <code>repeated .genetic.Department dept = 5;</code>
       */
      public java.util.List<cr.tec.genetic.struct.EmployeeProto.Department.Builder> 
           getDeptBuilderList() {
        return getDeptFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          cr.tec.genetic.struct.EmployeeProto.Department, cr.tec.genetic.struct.EmployeeProto.Department.Builder, cr.tec.genetic.struct.EmployeeProto.DepartmentOrBuilder> 
          getDeptFieldBuilder() {
        if (deptBuilder_ == null) {
          deptBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              cr.tec.genetic.struct.EmployeeProto.Department, cr.tec.genetic.struct.EmployeeProto.Department.Builder, cr.tec.genetic.struct.EmployeeProto.DepartmentOrBuilder>(
                  dept_,
                  ((bitField0_ & 0x00000010) == 0x00000010),
                  getParentForChildren(),
                  isClean());
          dept_ = null;
        }
        return deptBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:genetic.Employee)
    }

    // @@protoc_insertion_point(class_scope:genetic.Employee)
    private static final cr.tec.genetic.struct.EmployeeProto.Employee DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cr.tec.genetic.struct.EmployeeProto.Employee();
    }

    public static cr.tec.genetic.struct.EmployeeProto.Employee getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Employee>
        PARSER = new com.google.protobuf.AbstractParser<Employee>() {
      public Employee parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Employee(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Employee> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Employee> getParserForType() {
      return PARSER;
    }

    public cr.tec.genetic.struct.EmployeeProto.Employee getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface DepartmentOrBuilder extends
      // @@protoc_insertion_point(interface_extends:genetic.Department)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 deptid = 1;</code>
     */
    int getDeptid();

    /**
     * <code>string deptname = 2;</code>
     */
    java.lang.String getDeptname();
    /**
     * <code>string deptname = 2;</code>
     */
    com.google.protobuf.ByteString
        getDeptnameBytes();
  }
  /**
   * Protobuf type {@code genetic.Department}
   */
  public  static final class Department extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:genetic.Department)
      DepartmentOrBuilder {
    // Use Department.newBuilder() to construct.
    private Department(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Department() {
      deptid_ = 0;
      deptname_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Department(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              deptid_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              deptname_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cr.tec.genetic.struct.EmployeeProto.internal_static_genetic_Department_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cr.tec.genetic.struct.EmployeeProto.internal_static_genetic_Department_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cr.tec.genetic.struct.EmployeeProto.Department.class, cr.tec.genetic.struct.EmployeeProto.Department.Builder.class);
    }

    public static final int DEPTID_FIELD_NUMBER = 1;
    private int deptid_;
    /**
     * <code>int32 deptid = 1;</code>
     */
    public int getDeptid() {
      return deptid_;
    }

    public static final int DEPTNAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object deptname_;
    /**
     * <code>string deptname = 2;</code>
     */
    public java.lang.String getDeptname() {
      java.lang.Object ref = deptname_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        deptname_ = s;
        return s;
      }
    }
    /**
     * <code>string deptname = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDeptnameBytes() {
      java.lang.Object ref = deptname_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deptname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (deptid_ != 0) {
        output.writeInt32(1, deptid_);
      }
      if (!getDeptnameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, deptname_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (deptid_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, deptid_);
      }
      if (!getDeptnameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, deptname_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cr.tec.genetic.struct.EmployeeProto.Department)) {
        return super.equals(obj);
      }
      cr.tec.genetic.struct.EmployeeProto.Department other = (cr.tec.genetic.struct.EmployeeProto.Department) obj;

      boolean result = true;
      result = result && (getDeptid()
          == other.getDeptid());
      result = result && getDeptname()
          .equals(other.getDeptname());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DEPTID_FIELD_NUMBER;
      hash = (53 * hash) + getDeptid();
      hash = (37 * hash) + DEPTNAME_FIELD_NUMBER;
      hash = (53 * hash) + getDeptname().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cr.tec.genetic.struct.EmployeeProto.Department parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cr.tec.genetic.struct.EmployeeProto.Department parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cr.tec.genetic.struct.EmployeeProto.Department parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cr.tec.genetic.struct.EmployeeProto.Department parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cr.tec.genetic.struct.EmployeeProto.Department parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cr.tec.genetic.struct.EmployeeProto.Department parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cr.tec.genetic.struct.EmployeeProto.Department parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cr.tec.genetic.struct.EmployeeProto.Department parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cr.tec.genetic.struct.EmployeeProto.Department parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cr.tec.genetic.struct.EmployeeProto.Department parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cr.tec.genetic.struct.EmployeeProto.Department parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cr.tec.genetic.struct.EmployeeProto.Department parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cr.tec.genetic.struct.EmployeeProto.Department prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code genetic.Department}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:genetic.Department)
        cr.tec.genetic.struct.EmployeeProto.DepartmentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cr.tec.genetic.struct.EmployeeProto.internal_static_genetic_Department_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cr.tec.genetic.struct.EmployeeProto.internal_static_genetic_Department_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cr.tec.genetic.struct.EmployeeProto.Department.class, cr.tec.genetic.struct.EmployeeProto.Department.Builder.class);
      }

      // Construct using cr.tec.genetic.struct.EmployeeProto.Department.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        deptid_ = 0;

        deptname_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cr.tec.genetic.struct.EmployeeProto.internal_static_genetic_Department_descriptor;
      }

      public cr.tec.genetic.struct.EmployeeProto.Department getDefaultInstanceForType() {
        return cr.tec.genetic.struct.EmployeeProto.Department.getDefaultInstance();
      }

      public cr.tec.genetic.struct.EmployeeProto.Department build() {
        cr.tec.genetic.struct.EmployeeProto.Department result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cr.tec.genetic.struct.EmployeeProto.Department buildPartial() {
        cr.tec.genetic.struct.EmployeeProto.Department result = new cr.tec.genetic.struct.EmployeeProto.Department(this);
        result.deptid_ = deptid_;
        result.deptname_ = deptname_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cr.tec.genetic.struct.EmployeeProto.Department) {
          return mergeFrom((cr.tec.genetic.struct.EmployeeProto.Department)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cr.tec.genetic.struct.EmployeeProto.Department other) {
        if (other == cr.tec.genetic.struct.EmployeeProto.Department.getDefaultInstance()) return this;
        if (other.getDeptid() != 0) {
          setDeptid(other.getDeptid());
        }
        if (!other.getDeptname().isEmpty()) {
          deptname_ = other.deptname_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cr.tec.genetic.struct.EmployeeProto.Department parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cr.tec.genetic.struct.EmployeeProto.Department) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int deptid_ ;
      /**
       * <code>int32 deptid = 1;</code>
       */
      public int getDeptid() {
        return deptid_;
      }
      /**
       * <code>int32 deptid = 1;</code>
       */
      public Builder setDeptid(int value) {
        
        deptid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 deptid = 1;</code>
       */
      public Builder clearDeptid() {
        
        deptid_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object deptname_ = "";
      /**
       * <code>string deptname = 2;</code>
       */
      public java.lang.String getDeptname() {
        java.lang.Object ref = deptname_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          deptname_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string deptname = 2;</code>
       */
      public com.google.protobuf.ByteString
          getDeptnameBytes() {
        java.lang.Object ref = deptname_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          deptname_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string deptname = 2;</code>
       */
      public Builder setDeptname(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        deptname_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string deptname = 2;</code>
       */
      public Builder clearDeptname() {
        
        deptname_ = getDefaultInstance().getDeptname();
        onChanged();
        return this;
      }
      /**
       * <code>string deptname = 2;</code>
       */
      public Builder setDeptnameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        deptname_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:genetic.Department)
    }

    // @@protoc_insertion_point(class_scope:genetic.Department)
    private static final cr.tec.genetic.struct.EmployeeProto.Department DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cr.tec.genetic.struct.EmployeeProto.Department();
    }

    public static cr.tec.genetic.struct.EmployeeProto.Department getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Department>
        PARSER = new com.google.protobuf.AbstractParser<Department>() {
      public Department parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Department(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Department> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Department> getParserForType() {
      return PARSER;
    }

    public cr.tec.genetic.struct.EmployeeProto.Department getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_genetic_Employee_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_genetic_Employee_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_genetic_Department_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_genetic_Department_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n&cr/tec/genetic/protobuf/Employee.proto" +
      "\022\007genetic\"n\n\010Employee\022\021\n\tfirstname\030\001 \001(\t" +
      "\022\020\n\010lastname\030\002 \001(\t\022\n\n\002id\030\003 \001(\005\022\016\n\006salary" +
      "\030\004 \001(\001\022!\n\004dept\030\005 \003(\0132\023.genetic.Departmen" +
      "t\".\n\nDepartment\022\016\n\006deptid\030\001 \001(\005\022\020\n\010deptn" +
      "ame\030\002 \001(\tB&\n\025cr.tec.genetic.structB\rEmpl" +
      "oyeeProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_genetic_Employee_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_genetic_Employee_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_genetic_Employee_descriptor,
        new java.lang.String[] { "Firstname", "Lastname", "Id", "Salary", "Dept", });
    internal_static_genetic_Department_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_genetic_Department_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_genetic_Department_descriptor,
        new java.lang.String[] { "Deptid", "Deptname", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
